import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'

import Link from "next/link";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Typography } from "antd";
import Header from "./components/Header";
import TextArea from "./components/TextArea";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AntdRegistry>
        <body className={inter.className}>
          <Header/>
          {children}
          <TextArea />
        </body>
      </AntdRegistry>
    </html>
  );
}
